### ISSUE TITLE
Failure with matplotlib 3.6.0 prereleases 

### ISSUE THREAD

**Issue by mgxd** [danjgale/surfplot#16]
This came up while prerelease testing - was able to reproduce with the included example:
```
Traceback (most recent call last):
  File "/Users/mathiasg/code/surfplot/tutorials/examples/plot_example_01.py", line 40, in <module>
    fig = p.build(cbar_kws=cbar_kws)
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/surfplot/plotting.py", line 510, in build
    self._add_colorbars(**cbar_kws)
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/surfplot/plotting.py", line 451, in _add_colorbars
    cb = plt.colorbar(sm, ticks=ticks, location=location, 
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/matplotlib/pyplot.py", line 2053, in colorbar
    ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kwargs)
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/matplotlib/figure.py", line 1256, in colorbar
    raise ValueError(
ValueError: Unable to determine Axes to steal space for Colorbar. Either provide the *cax* argument to use as the Axes for the Colorbar, provide the *ax* argument to steal space from it, or add *mappable* to an Axes.
```

#### relevant versions:
brainspace==0.1.4
matplotlib==3.6.0rc2
vtk==9.2.0rc2

**Comment by emdupre** [comment]
Just to +1 this -- I hit the same issue in my own environment with MPL 3.6.0 installed. Now that this is an official MPL release, I imagine quite a few other folks might also benefit from the fix !

Thanks as always for surfplot, @danjgale !

**Comment by danjgale** [comment]
Hi @mgxd, thanks for this issue and I will get to review + pulling your PR shortly. Totally swamped at moment, but hoping to have more time in the coming weeks.  @emdupre Good to know, I will make this a priority

**Comment by danjgale** [comment]
@mgxd and @emdupre this has been merged to main now. Thank you so much for you contribution and your patience!

**Comment by danjgale** [comment]
I may have spoken too soon, as I can no longer get it working with 3.6.0; the same error still occurs. However, it works with as expected with 3.6.2.

**Comment by emdupre** [comment]
Thank you, @danjgale !!
